version: 2.1

orbs:
  win: circleci/windows@4.1.1 # The Windows orb gives you everything you need to start using the Windows executor

jobs:
  build: # name of your job
    executor: win/server-2022 # use one of the executors defined within the windows orb

    steps:
      # Commands are run in a Windows virtual machine environment
      - add_ssh_keys:
        fingerprints: ["ee:d1:69:f5:a9:a0:52:42:73:8e:4a:52:09:5b:62:ca"]
      - checkout
      - run: Write-Host 'Hello, Windows'